language: java

# script:
# - ant;
# - ant test;

sudo: required

services:
  - docker

before_install:
  - docker build -t Christiaan52/green .

script:
  - docker run Christiaan52/green /bin/sh -c "ant; ant test"
